name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  build:
    name: Building for ${{ matrix.name }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - macos-13
          - windows-latest
        include:
          - os: ubuntu-latest
            name: linux
            suffix: ''
            artifact-name: lynx-backend
            arch: x64
          - os: macos-14
            name: macos
            suffix: ''
            artifact-name: lynx-backend
            arch: arm64
          - os: macos-13
            name: macos
            suffix: ''
            artifact-name: lynx-backend
            arch: x64
          - os: windows-latest
            name: windows
            suffix: .exe
            artifact-name: lynx-backend.exe
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle build
        run: ./gradlew clean test nativeCompile

      - name: Rename to use the platform and architecture
        run: |
          mkdir -p dist
          uname -a
          mv build/native/nativeCompile/${{ matrix.artifact-name }} dist/lynx-backend-${{ matrix.name }}-${{ matrix.arch }}${{ matrix.suffix }}

      - name: Upload Native Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lynx-backend-${{ matrix.name }}-${{ matrix.arch }}${{ matrix.suffix }}
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Clone the repository
      - uses: actions/download-artifact@v4
        name: Download the build artifact
        with:
          merge-multiple: true
          pattern: dist-*
          path: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: 0.0.1-SNAPSHOT
          body: |
            Release ${{ github.ref }}
